### ISSUE TITLE
[1.20.4] Unable to play sound on copper door and trapdoor variants

### ISSUE THREAD

**Issue by Soufre** [JosiahFu/DoorJam#1]
Like the title says; when I open and close a _normal_ copper door/trapdoor, it plays its unique sounds. However, it isn't the case when I do the same with **its variants** (exposed, weathered and oxidised). 

I can verify it's not a compatibility issue with other mods, since I'm only using the latest Fabric API jar with it.

**Comment by Soufre** [comment]
Okay so, the issue only exists with version 1.1.4 of Door Jam. **1.1.3 has no problems as far as I know.**

**Comment by ThePotatoArchivist** [comment]
Thanks for submitting the issue! I will look into it, it might be due to the sound changes made to the copper door in one snapshot
